---
- hosts: webservers
  become: yes
  tasks:
  - name: calling jenkins job
    jenkins_job:
      config: "{{ lookup('file','/var/lib/jenkins/jobs/jenkins-ansible/config.xml') }}"
      name: test
      user: anand
      password: kumar
      state: present
      url: http://54.152.209.209:8080
