---
- hosts: webservers
  become: yes
  tasks:
  - name:
    jenkins_job:
      config: "{{ lookup('file', 'templates/test.xml') }}"
      name: test
      user: anand
      password: kumar
      url: http://54.152.209.209:8080
      state: present
      enabled: true
